name: PierreFoisyIllustrations
favicon: null
layout_spectrum: 0.2880820834543556
typography_spectrum: 0.13276592013426125
title: Pierre Foisy Illustrations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8478501131758094
  lightness: 0.6055497922934592
  saturation: 0.36098781460896134
  rhythmicContrast: 0.30471846694126725
purpose: []
